POST http://localhost:3001/organization
content-type: application/json
authorization: a6c7b8831ff85b1243708906d5f266d2cba7e7d7db21f2085d2082764ac20056

{
    "name":"test3",
    "shortDesc":"This is a shot description",
    "longDesc":"This is a long description"
}