POST http://localhost:3001/user/login
Content-Type: application/json

{
    "email":"markkohler3@gmail.com",
    "password":"123456",
    "CSRF":"8e1969395b58d59fd9832f03f69000e5c9b869a4165c5eb1aab8f6a5a5df594c"
}