POST http://localhost:3001/rule
Authorization: 80b02d5074e5daa2cdf664498192b81fc3d51928a608869448e65ad8aa0454ec
Content-Type: application/json

{
    "name":"Rule 1",
    "shortDesc":"Rule 1 stuff",
    "longDesc":"Long rule 1 stuff"
}