POST http://localhost:3001/rule
Authorization: 7d63df8b08137950d6f433d82c3944bc31c06015b26d1d16bcefc2158bd5cff5
Content-Type: application/json

{
    "name":"Rule 2",
    "shortDesc":"Rule 2 stuff",
    "longDesc":"Long rule 2 stuff"
}