POST http://localhost:3001/organization
content-type: application/json
authorization: 4cc1aeac01c39472d6221eabcbab00a0c3209d26d72efe43fc704cd571892f74

{
    "name":"test12",
    "shortDesc":"This is a shot description",
    "longDesc":"This is a long description"
}