POST http://localhost:3001/user/login
Content-Type: application/json

{
    "email":"markkohler3@gmail.com",
    "password":"123456",
    "CSRF":"20d9eae316f276a3585f5d3a463e76689eecf2ceb4c232025f4c2ed44357a71b"
}